
export const EntityTypes = [
    { name: 'مشتری', id: 1 },
    { name: 'محصولات', id: 2 },
    { name: 'سازمان', id: 3 },
    { name: 'انبار', id: 4 },
    { name: 'کالاانباره', id: 5 },
    { name: 'تامین', id: 6 },
    { name: 'تامین کنندگان', id: 7 },
    { name: 'عرضه', id: 8 },
    { name: 'حواله', id: 9 },
    { name: 'سفارش', id: 10 },
    { name: 'جزییات سفارش', id: 11 },
    { name: 'سبد خرید', id: 12 },
    { name: ' آدرس', id: 13 },
    { name: 'ضمیمه', id: 14 },
    { name: 'اعلان ها', id: 15 },
    { name: 'باربری', id: 16 },
    { name: 'قرارداد باربری', id: 17 },
    { name: 'قرارداد باربری', id: 18 },
    { name: 'فاکتور', id: 19 },
    { name: 'پرداخت', id: 20 },
    { name: 'اعتبار', id: 21 },
    { name: 'اعضای اعتبار', id: 22 },

]

// public enum EntityTypes
// {
//     Customer = 1,
//     Product,
//     Organization,
//     Warehouse,
//     ProductWareHouse,
//     Supply,
//     Supplier,
//     ProductSupply,
//     Shipping,
//     Order,
//     OrderDetail,
//     ShoppingCart,
//     Address,
//     Attachment,
//     News,
//     ShippingCompany,
//     ShippingContract,
//     ShippingReport,
//     Invoice,
//     Payment,
//     Credit,
//     CreditMember
// }
